defaults:
  - _self_
  - algorithm: adam
  - env: balancing_stick
  # override this to use the new list sweeper:
  - override hydra/sweeper: list

hydra:
  mode: MULTIRUN
  sweeper:
    # standard grid search
    grid_params:
      env: 5_clubs_juggling, balancing_stick
    # additional list sweeper
    list_params:
      algorithm.lr: 0.001, 0.0001
      algorithm.beta_1: [0.9, 0.99]  # both notations work
    ablative_params:
      - algorithm.beta_2: 0.5
        algorithm.epsilon: 1e-4
      - algorithm.beta_1: 0.3
