defaults:
  - _self_
  - db: mysql
  - override hydra/sweeper: list

hydra:
  mode: MULTIRUN
  sweeper:
    grid_params:
      db.pass: secret, open
    list_params:
      db.driver: lazy_lollo, bruno
      db.car: toyota, honda
